export const FILL_USERS_DATA = "FILL_USERS_DATA";
export const ADD_ERROR_EVENT = "ADD_ERROR_EVENT";
export const DELETE_ERROR_EVENT = "DELETE_ERROR_EVENT";

export const ON_CHANGE_LIMIT = "ON_CHANGE_LIMIT";
export const ON_CHANGE_USER_COUNT = "ON_CHANGE_USER_COUNT";
export const SELECT_USER_STATUS = "SELECT_USER_STATUS";
export const SUBMIT_FILTER_DATA = "SUBMIT_FILTER_DATA"
